### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by linsui** [agersant/polaris-android#23]
Could you please publish this app on F-Droid? Thanks!

**Comment by agersant** [comment]
Thank you for the suggestion.

I just took a look at the process to publish apps on F-Droid and it seems fairly involved - I don't think this is something I want to invest a lot of time into.

I will keep the issue open and accept (reasonable) Pull Requests working towards this goal.

**Comment by linsui** [comment]
Thanks! If there is no non-free components in this app (e.g. firebase) it will be easy. I'll submit an [rfp](https://gitlab.com/fdroid/rfp/-/issues/1364) and bot will tell if there is any problem.

**Comment by agersant** [comment]
Thanks! There are no analytics of any kind in the client so hopefully it should work out.

**Comment by IzzySoft** [comment]
Thanks for considering! We'll try to keep the load low :wink: Would be great if you could establish [Fastlane structures](https://gitlab.com/snippets/1895688) (just the structures, the binaries are not needed) and then [tag your releases](https://github.com/agersant/polaris-android/releases). Reasons for the former are described behind its link – and the latter helps to tell which commit(s) exactly to build as well as to detect when new versions are available.

**Comment by agersant** [comment]
Done and done!
https://github.com/agersant/polaris-android/pull/24
https://github.com/agersant/polaris-android/releases/tag/v0.8.4

**Comment by IzzySoft** [comment]
Thanks! Checked, looks great! I've completed metadata on the RFP and marked it ready for our packagers then.

@linsui as usual, if no packager shows up within 2 weeks, you know how to reach me :wink:

**Comment by linsui** [comment]
Thanks!

**Comment by Bubu** [comment]
It's available in F-Droid now. https://f-droid.org/en/packages/agersant.polaris/

Unfortunately the app contains no icon in the fastlane metadata, so f-droid only shows a broken image link, can you add an icon and make a new release including this change?

**Comment by agersant** [comment]
Thanks! I just released 0.8.5 with an icon added.
