### ISSUE TITLE
F-Droid is not distributing new releases of Polaris Android

### ISSUE THREAD

**Issue by agersant** [agersant/polaris-android#28]
I just noticed that the F-Droid catalogue still lists version 0.8.4 of this app: https://f-droid.org/packages/agersant.polaris/

@linsui @IzzySoft Do you happen to know if something is required on my part for this to happen? I was under the impression that git tags and fastlane changelogs for new releases were the only requirements.

**Comment by IzzySoft** [comment]
```gradle
        versionCode Integer.valueOf(System.env.VERSION_CODE ?: 1)
        versionName "0.8.6"
```

Well, no `versionCode` matching `/^\s*versionCode\s+(\d+)/` – so our updater ignores it. It only parses `build.gradle` – it does not run `gradlew` or something.

**Comment by agersant** [comment]
Ah that makes sense, thank you very much!
Not sure yet how I'll make this work nicely with CI but it gives me a clear target.

**Comment by IzzySoft** [comment]
Should you run into a "dead end" and have questions, just ask them here. I'll stay subscribed to this issue. Best luck!

**Comment by agersant** [comment]
Thank you! I do have a small follow-up question.

While I'm in this space, I am considering using version codes in human-readable range for future releases (they are currently Github run IDs, very large numbers). Would this transition (ie. next release would have a lower version code than current one) cause any issues with F-Droid?

EDIT: Nevermind, it would break Google Play Store (https://developer.android.com/studio/publish/versioning) - looks like I am stuck with high numbers forever :D

**Comment by IzzySoft** [comment]
You can always *increase* them – but never *decrease* again, or your users would need to uninstall and reinstall (and the F-Droid updater would never pull your updates, as it would consider them "older"). Then, they'd still get the old versions back unless they are purged from the repos. You already found out: this number is what Android uses internally to decide which APK is newer (the higher the number, the newer)…

**Comment by agersant** [comment]
I think things should be in order now. Tags now point to commits where `build.gradle` files has readable versionCodes and versionNames. How frequently does the updater run?

**Comment by IzzySoft** [comment]
I wish there were a schedule published… The updater itself AFAIK is a cron job, schedules once or twice a day (so you could study its output, [see here](https://gitlab.com/snippets/1896503) for the corresponding URLs). Build and Signing are a different pair of shoes; the latter for sure is manual (with the index update triggered once signing was completed), and the former seems to be manual as well (as it seems to run rather irregularly).

Still: To see if the issue was solved, watching the updater (and cross-checking `CurrentVersion`/`CurrentVersionCode` at the end of the YAML) should match the bill.

**Comment by agersant** [comment]
https://f-droid.org/repo/status/checkupdates.json seems very out of date, the timestamp at the top is for a run in November.

I did find my way to logs for the update job itself, and compared what it said two days ago VS last night.

Two days ago:
https://gitlab.com/fdroid/fdroiddata/-/jobs/904482440
> 2020-12-11 03:09:44,836 INFO: Processing agersant.polaris
> 2020-12-11 03:09:56,953 WARNING: ...agersant.polaris : Couldn't find package ID

Latest run
https://gitlab.com/fdroid/fdroiddata/-/jobs/907525724
> 2020-12-13 03:08:36,598 INFO: Processing agersant.polaris
> 2020-12-13 03:08:43,906 INFO: ...up to date

I think this last run have been while I was still working on cleaning house. I'll keep an eye on the next one which starts in an hour and a half.

**Comment by IzzySoft** [comment]
Always remember the updater is looking at the tags, not at `HEAD` (unless that's where the latest tag points to, of course).

**Comment by agersant** [comment]
https://gitlab.com/fdroid/fdroiddata/-/jobs/908363050
```
2020-12-14 03:09:53,632 INFO: Processing agersant.polaris
2020-12-14 03:10:05,132 INFO: ...updating to version 0.8.6 (415293112)
2020-12-14 03:10:05,133 INFO: ...auto-generating build for 0.8.6
2020-12-14 03:10:05,243 INFO: Commiting update for metadata/agersant.polaris.yml
Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
[detached HEAD 4b21c9d265] Update Polaris to 0.8.6 (415293112)
 1 file changed, 9 insertions(+), 2 deletions(-)
```

🥳

**Comment by IzzySoft** [comment]
Congrats! Guess that did it then :smiley:

**Comment by agersant** [comment]
The build hasn't showed up yet on https://f-droid.org/packages/agersant.polaris/ but I imagine it's somewhere on the way now.

**Comment by IzzySoft** [comment]
There hasn't been a new index yet, so it cannot yet have shown up. Ciaran has to sign the APK first (which is done manually on an air-gapped machine).

**Comment by agersant** [comment]
New build has been published on the store 🚀

**Comment by licaon-kter** [comment]
FYI: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7991/diffs#2e4a4ab57b3aec17c39c3a4f0af5a4d8f7ec487f_46_30

**Comment by agersant** [comment]
Thanks for fixing this!
