### ISSUE TITLE
Android App only Showing One Collection

### ISSUE THREAD

**Issue by Teflon98** [agersant/polaris-android#48]
Greetings

Using the web interface, I can see my two collections.

Using the app, only one collection is there.  I also see some random album along with that one collection.

I have tried clearing out the cache, uninstalling, reinstalling.

Please keep up the great work!

**Comment by agersant** [comment]
Hello and thank you for the report!

I am unable to reproduce this issue on my end, I can see multiple music directories listed in the `Browse` tab. A few questions that may help with troubleshooting:

- Did you install the Android app from the Google Play Store or F-droid?
- In the `Browse` tab of the mobile app, try pulling the screen from the top to refresh.
- What is the name of the missing collection? (could be a bug with special characters not being handled correctly)
- Could you clarify what you mean by "some random album along with that one collection"?

**Comment by Teflon98** [comment]
Thank you for the quick response:

- Installed from Google Play.
- I have tried pulling the screen to refresh several times.
- When I first made the collection, it had spaces in it.  I renamed it with no spaces - No luck.  I made a new collection with a new name and got rid of the old one - No luck.
- The random album were actually some loose tracks sitting in the root of the collection that wasn't showing up. It seems instead of showing that collection and it's folders, it only showed the loose tracks sitting in the root.

For the Android app: When I have uninstalled and reinstalled the app, it doesn't seem to completely remove the previous settings.  When I reinstall and then launch the app, my previous settings are there and logged in.

Thanks again for your work on this!

**Comment by agersant** [comment]
What a strange bug this is 😦, I am honestly not sure what to suggest from here. Settings not clearing upon reinstall is especially strange as that is entirely managed by Android.

Would you be able to send the `db.sqlite`  file from your Polaris install so I can try and reproduce the issue locally? My email is `antoine.gersant@lesforges.org`.
Be aware that this file does include some private information (`ydns` credentials if you use it, `lastfm` session key if you linked your account, file paths and song metadata for your entire collection, hashed credentials for Polaris users). 
The location of the file depends on your OS and installation method. On Windows it would be inside `%localappdata%\Permafrost\Polaris`.

**Comment by Teflon98** [comment]
Sorry for not responding sooner.

Thank you for your response and your efforts.  Right now, I am not going to pursue using Polaris.  I think you have the framework of something great but it's not working enough for me right now.

I look forward to seeing what some additional development produces.

If there was an Android Auto version, that would be amazing.  Also, if there was a search button in the Android app, that would be amazing too.

Keep up the amazing work you're doing: It is appreciated.
