### ISSUE TITLE
Unable to connect: An unknown error occured

### ISSUE THREAD

**Issue by jtrees** [agersant/polaris-android#49]
I just installed Polaris on my server. I am able to access the instance (on LAN) via the web interface but connecting with the Android app doesn't work. No matter what I enter for the server URL I always get the following message: "An unknown error occured"

Here are some of the URL formats I tried:

- http://foo:5050
- http://foo
- foo

Note: There is no TLD involved.

**EDIT**

I was finally able to connect via the IP address, like so:

- 192.168.178.42:5050

**Comment by agersant** [comment]
This sounds like an issue within the Flutter/Android network stack. Polaris Android adds `http://` when the URL has no protocol specified, it's used as-is other than that.

Are you able to access `http://foo:5050` from a mobile browser?

**Comment by jtrees** [comment]
Oh, you're right. Can't get there from a browser either. Guess this is a non-issue then.
