### ISSUE TITLE
Tracks missing in library

### ISSUE THREAD

**Issue by jtrees** [agersant/polaris-android#50]
I noticed that some of my music does not turn up in the app. The problem seems to be that folders with files in them no longer have their subfolders searched.

For example:

```
RootCollection/
  Alice/
    RandomTrack01.mp3
    RandomTrack02.mp3
  Bob/
    FirstAlbum/
      01Intro.mp3
      02Outro.mp3
    RandomSingle.mp3 <-- causes all album folders to be ignored
  Charlie/
    BestAlbum/
      01OnlyTrack.mp3
```

With the above hierarchy all music by Alice and Charlie will be there but only `RandomSingle.mp3` from Bob will be available. `FirstAlbum` and all it's tracks seem to be hidden.

**Comment by agersant** [comment]
I am able to reproduce this, investigating 🔍

**Comment by agersant** [comment]
Fixed in bce3abbacacb3515d734090c58b3851451a5c899

**Comment by jtrees** [comment]
Thanks!

**Comment by jtrees** [comment]
Just got the new release on F-Droid. It works! Thanks again.
