### ISSUE TITLE
"Media playback error"

### ISSUE THREAD

**Issue by khromov** [agersant/polaris-android#8]
Trying to play some tracks but after adding them to queue, a message "A media playback error occured" shows up and the songs are not played.

I'm using the default port, so I've added the server as: `mydomain.com:5050`

![screenshot_20170801-200445](https://user-images.githubusercontent.com/1207507/28839848-40d221b2-76f5-11e7-9183-39b162f66526.png)
![screenshot_20170801-200742](https://user-images.githubusercontent.com/1207507/28839853-43877a24-76f5-11e7-86a1-63a08a48b314.png)

**Comment by agersant** [comment]
Thanks for the bug report! A couple questions to help me track this down:

- Does playback from this server work in the web client?
- In your screenshot I can see some "downloading" icons on a couple playlist tracks. Do some of those eventually become "downloaded" icons? That one looks like an SD card.
- What format is your music stored as?
